name: Build and test

on:
  push:
    branches: 
      - master
  schedule:
    - cron:  '55 * * * *'

jobs:
  test:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@master
      
    - name: Setup .NET
      uses: actions/setup-dotnet@master
        
    - name: Setup NuGet
      uses: nuget/setup-nuget@v1
        
    - name: Restore NuGet packages:
      run: nuget restore GenericPool.sln
      shell: cmd
      
    - name: Build
      run: dotnet build GenericPool.sln
      shell: cmd
